import type { Metadata } from "next";
import { Code, P, Section } from "@/components/CaseStudy";
import { NoteLayout } from "@/components/Note";
import { ProvenanceBadge } from "@/components/Provenance";
import { noteBySlug } from "@/lib/notes";
import { pageMeta } from "@/lib/meta";
import { blob } from "@/lib/site";

const note = noteBySlug("wrong-template-fallback")!;
export const metadata: Metadata = pageMeta({
  title: note.title, description: note.dek, path: `/notes/${note.slug}`,
  type: "article", publishedTime: note.date,
});

export default function EngineeringNote() {
  return (
    <NoteLayout slug={note.slug}>
      <P>Prep has a seeded curriculum for when AI generation is unavailable or fails. That curriculum is frontend-focused. Supporting a backend role meant I also had to account for a failed request handing someone frontend study material.</P>
      <Section id="scope" heading="The template still has to fit the request">
        <P>I could keep the role list frontend-only, build a backend catalog, or let people request backend plans while making the fallback mismatch visible. I shipped the third option. A backend catalog is still content I need to write.</P>
        <P>The resulting plan can be opened and used, but that doesn&rsquo;t make it the backend curriculum the person asked for. A generic &ldquo;using a template&rdquo; message would leave out the important part.</P>
        <p className="mt-4"><ProvenanceBadge href={blob("prep", "memory.md?plain=1", "L1483-L1501")} source="Development log · backend role and fallback scope" /></p>
      </Section>
      <Section id="source" heading="Record how the plan was made">
        <P>The generation route stores <Code>generated_from</Code> as <Code>ai</Code> or <Code>seed</Code>. The mismatch check uses that value alongside the requested role. A backend plan generated by the model doesn&rsquo;t get the warning just because the fallback catalog is frontend-focused.</P>
        <P>Older roadmaps have no recorded source. I leave that value unknown instead of assuming they came from the model or the template.</P>
        <p className="mt-4 flex flex-col items-start gap-2">
          <ProvenanceBadge href={blob("prep", "app/api/roadmaps/generate/route.ts")} source="Persisting the generation source" />
          <ProvenanceBadge href={blob("prep", "lib/seed/catalog.ts")} source="Catalog scope and templateMismatch()" />
        </p>
      </Section>
      <Section id="notice" heading="Keep the warning with the plan">
        <P>The roadmap shows a template-mismatch notice, and the print view carries it too. Someone reading the exported plan should have the same context as someone using the app.</P>
        <P>I don&rsquo;t flag fullstack plans because the frontend catalog covers part of that role. That&rsquo;s a deliberate limit of this check: it identifies the backend mismatch, not every gap in a study plan.</P>
        <p className="mt-4 flex flex-col items-start gap-2">
          <ProvenanceBadge href={blob("prep", "app/(app)/roadmap/[id]/page.tsx")} source="Roadmap mismatch notice" />
          <ProvenanceBadge href={blob("prep", "app/(print)/roadmap/[id]/print/page.tsx")} source="The same notice in the print view" />
        </p>
      </Section>
    </NoteLayout>
  );
}
